##The website title
name: luksan's observations
##Markdown processor
markdown: redcarpet
##syntax highlighter
highlighter: rouge

##define base_url for valid usage in sitemap.xml and robots.txt
base_url: http://luksan.github.io
sass:
  sass_dir: _sass
  style: :compressed
paginate: 5
paginate_path: "page:num"
##The website description (to be used in meta tags)
description: Experiments in programming, electronics, photograpy, and whatever I care to document.
##Some frequently used keywords on your website
keywords: 

##define this for disqus comment support
#disqus: disqusdomain

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: analyticsDomain

##Some commonly used links
links:
  email: luksan@gmail.com
  github: luksan

##put desired image in img/ directory and set the value accordingly. If not defined, a placeholder image will be used.
#about_image: placeholder.jpg
